//  createSlice helps us define Redux logic (state + reducers + actions) in one place.
import { createSlice } from "@reduxjs/toolkit";
// This defines the shape (structure) of a user object.
import { IUser } from "@/models/user.model";

// This ensures type safety (helps catch errors during development).
interface userState {
    // userData will either be an IUser object OR null (when no user is logged in).
    userData: IUser | null;
}


// Defining the initial state of the slice. This must match the structure of userState.
const initialState: userState = {
    userData: null, // Initially, no user is stored, so it's null.
};


// Creating a slice of the Redux store. A "slice" is a piece of the global state with its own logic.
export const userSlice = createSlice({
    // This is used internally by Redux (e.g., for action types like "user/setUserData").
    name: "user",
    initialState,

    // Reducers are functions that define how the state can change. Each function here becomes an action + reducer automatically.
    reducers: {

        // This reducer updates the userData in the state. It takes the current state and an action as arguments.
        setUserData: (state, action) => {

            // Redux Toolkit uses Immer internally,
            // so we can "mutate" the state directly like this.
            // Under the hood, it creates an immutable update safely.
            state.userData = action.payload
        }
    },
});


// Exporting the action creator generated by createSlice.This allows components to dispatch this action like: dispatch(setUserData(user))
export const { setUserData } = userSlice.actions;


// Exporting the reducer function. This will be added to the Redux store configuration.
export default userSlice.reducer;